"""
Audit Logging Service with Data Scrubbing & Sanitization.
Never logs API keys, passwords, bearer tokens, or raw sensitive transcript content.
"""

import re
import logging
from typing import Optional, Union, Dict, Any
from sqlalchemy.orm import Session
from app.models.nhaa_models import AuditLog, User

logger = logging.getLogger("services.audit")

# Regex patterns for sensitive credentials & tokens
SENSITIVE_PATTERNS = [
    # API Keys / Bearer tokens / JWTs
    (re.compile(r"Bearer\s+[A-Za-z0-9\-_=]+\.[A-Za-z0-9\-_=]+\.?[A-Za-z0-9\-_.+/=]*", re.IGNORECASE), "[REDACTED_BEARER_TOKEN]"),
    (re.compile(r"AIzaSy[A-Za-z0-9\-_]{33}", re.IGNORECASE), "[REDACTED_GEMINI_KEY]"),
    (re.compile(r"gsk_[A-Za-z0-9]{32,}", re.IGNORECASE), "[REDACTED_GROQ_KEY]"),
    (re.compile(r"sk-[A-Za-z0-9\-_]{20,}", re.IGNORECASE), "[REDACTED_SECRET_KEY]"),
    (re.compile(r"(password|pwd|pass|secret|apiKey|api_key)[\"':=\s]+([^\s,;\"'\}]+)", re.IGNORECASE), r"\1: [REDACTED]"),
    # Phone numbers / Aadhaar numbers (12 digit pattern)
    (re.compile(r"\b\d{4}\s?\d{4}\s?\d{4}\b"), "[REDACTED_ID_NUMBER]"),
]


def sanitize_text(text: Optional[str], max_len: int = 500) -> str:
    """
    Sanitizes sensitive data from audit text rationale and details.
    Strips passwords, API keys, tokens, and trims excessive length.
    """
    if not text:
        return ""

    sanitized = str(text)
    for pattern, replacement in SENSITIVE_PATTERNS:
        sanitized = pattern.sub(replacement, sanitized)

    # Truncate to maximum permissible length to prevent DB bloat or log pollution
    if len(sanitized) > max_len:
        sanitized = sanitized[:max_len] + "... [TRUNCATED]"

    return sanitized


def record_audit_log(
    db: Session,
    action: str,
    rationale: Optional[str] = None,
    case_id: Optional[int] = None,
    user: Optional[User] = None,
    user_role: Optional[str] = None,
    ip_address: Optional[str] = None,
) -> AuditLog:
    """
    Creates a sanitized audit log entry in the database.
    """
    clean_action = sanitize_text(action, max_len=100)
    clean_rationale = sanitize_text(rationale, max_len=500)
    role = user.role if user else (user_role or "System")
    uid = user.id if user else None

    entry = AuditLog(
        case_id=case_id,
        user_id=uid,
        user_role=role,
        action=clean_action,
        rationale=clean_rationale,
        ip_address=ip_address,
    )

    try:
        db.add(entry)
        db.commit()
        db.refresh(entry)
        logger.info(
            "AUDIT LOG: [Action: %s] [User: %s (Role: %s)] [Case ID: %s] - %s",
            clean_action,
            user.username if user else "System",
            role,
            case_id or "N/A",
            clean_rationale,
        )
    except Exception as e:
        db.rollback()
        logger.error("Failed to write audit log to database: %s", e)

    return entry


def log_case_access(
    db: Session,
    case_id: int,
    user: Optional[User],
    rationale: Optional[str] = None,
    ip_address: Optional[str] = None,
) -> AuditLog:
    """Logs when an officer or operator views/accesses case records."""
    return record_audit_log(
        db=db,
        action="CASE_ACCESSED",
        rationale=rationale or f"Case accessed for review by {user.username if user else 'System'}.",
        case_id=case_id,
        user=user,
        ip_address=ip_address,
    )


def log_case_update(
    db: Session,
    case_id: int,
    user: Optional[User],
    old_status: Optional[str],
    new_status: Optional[str],
    priority: Optional[str] = None,
    notes: Optional[str] = None,
    ip_address: Optional[str] = None,
) -> AuditLog:
    """Logs triage updates or status changes for a case."""
    detail = f"Status changed: '{old_status}' -> '{new_status}'."
    if priority:
        detail += f" Priority: {priority}."
    if notes:
        detail += f" Officer notes: {notes}"

    return record_audit_log(
        db=db,
        action=f"CASE_TRIAGE_UPDATE",
        rationale=detail,
        case_id=case_id,
        user=user,
        ip_address=ip_address,
    )


def log_ai_recommendation(
    db: Session,
    case_id: int,
    engine_name: str,
    recommendation: str,
    risk_level: Optional[str] = None,
    confidence: Optional[float] = None,
) -> AuditLog:
    """Logs automated AI recommendations generated by Engine 1, Engine 2, or SVI."""
    detail = f"Generated by {engine_name}. Risk: {risk_level or 'N/A'}. Confidence: {confidence or 1.0:.2f}. Suggestion: {recommendation}"
    return record_audit_log(
        db=db,
        action=f"AI_RECOMMENDATION_RECORDED",
        rationale=detail,
        case_id=case_id,
        user_role="AI_ENGINE",
    )


def log_ai_override(
    db: Session,
    case_id: int,
    user: Optional[User],
    original_ai_verdict: str,
    overridden_verdict: str,
    rationale: str,
    ip_address: Optional[str] = None,
) -> AuditLog:
    """Logs manual human override of AI decision support recommendation."""
    detail = f"AI verdict '{original_ai_verdict}' overridden to '{overridden_verdict}'. Officer Rationale: {rationale}"
    return record_audit_log(
        db=db,
        action="AI_RECOMMENDATION_OVERRIDDEN",
        rationale=detail,
        case_id=case_id,
        user=user,
        ip_address=ip_address,
    )


def log_case_escalation(
    db: Session,
    case_id: int,
    user: Optional[User],
    escalation_tier: str,
    rationale: str,
    ip_address: Optional[str] = None,
) -> AuditLog:
    """Logs emergency escalation to senior Nodal Officer or PCR unit."""
    detail = f"Escalated to {escalation_tier}. Reason: {rationale}"
    return record_audit_log(
        db=db,
        action="CASE_ESCALATED",
        rationale=detail,
        case_id=case_id,
        user=user,
        ip_address=ip_address,
    )
